on:
  push:
    branches: [main]
  pull_request:
name: lint
jobs:
  style:
    runs-on: ubuntu-latest
    name: ${{ matrix.toolchain }}
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta]
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: cargo fmt --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - uses: actions/checkout@v3
      - name: cargo doc
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: doc
          args: --no-deps --all-features
        env:
          RUSTDOCFLAGS: --cfg docsrs
